name: grantproof
description: Premium mobile evidence capture demo for NGOs and donor reporting.
publish_to: 'none'
version: 1.0.8+8

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  path: ^1.9.0
  flutter_appauth: ^8.0.3
  http: ^1.2.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
